spring.application.name=pfeapp

server.port=8085
spring.datasource.url=jdbc:postgresql://localhost:5432/pfe_db
spring.datasource.username=postgres
spring.datasource.password=maysae13

<!--spring.security.user.name=ayoub-->
<!--spring.security.user.password=ayoub -->

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

